# Generated by Django 5.1.1 on 2024-09-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Image',
            new_name='image',
        ),
    ]
