# Generated by Django 5.1.1 on 2024-09-15 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_animal_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypost',
            options={'ordering': ['-created_at'], 'verbose_name': 'CategoryPost', 'verbose_name_plural': 'CategoryPosts'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='app.shelter'),
        ),
    ]
